universities:
  # - princeton.edu
  # - mit.edu
  # - harvard.edu
  # - stanford.edu√ü
  # - yale.edu
  # - upenn.edu
  # - caltech.edu
  # - uchicago.edu
  # - jhu.edu
  # - northwestern.edu
  # - http://www.yone.ac.jp/
  # - http://www.unad.edu.do
  # - http://www.isiaroma.it/
  # - https://www.usma.ac.pa/
  # - http://www.tuat.ac.jp/en/
  # - http://www.nagpuruniversity.org/
  # - http://www.ytu.edu.mm/
  # - http://www.afu.edu.np/
  # - http://www.do-bunkyodai.ac.jp/
  # - https://www.pfw.edu/
  # - http://www.zirve.edu.tr/en/
  # - https://www.oakton.edu/
  # - https://www.unmo.ba
  # - https://www.cityu.edu.mo
  # - https://www.ekof.bg.ac.rs
  - http://www.jntuk.edu.in/
  # - http://rtc.edu/
  # - http://www.kgsu.ru/
  # - http://www2.howard.edu/
  # - https://www.xhu.edu.cn
  # - https://www.jhu.edu


